<?php
/**
 * Created by PhpStorm.
 * User: chenhg5
 * Date: 2018/4/21
 * Time: 上午11:37
 */

namespace HttpServer\Module\Server;


class EpollModel extends BaseModel
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        // epoll/kqueue 模型 libevent 扩展 libev 事件库
//        if ($mode == EPOLL_KQUEUE_MODE) {
//
//        }
    }
}