<?php

namespace HttpServer\Module\Server;


class MultiProcessModel extends BaseModel
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        // 多进程固定进程抢占式模型 进程间通信
        for ($i = 0; $i < 32; $i++) {
            if (pcntl_fork() == 0) {
                while (1) {
                    $conn = stream_socket_accept($this->serv);
                    echo "process id: " . posix_getpid() . "\n";
                    $request = @fread($conn, 30000);  // 粗暴的设置长度
                    echo "connected\n";
                    echo "request info: \n\n" . $request . "\n";

                    $response = <<<s
HTTP/1.1 200 OK
Server: Microsoft-IIS/4.0.1
Date: Mon, 5 Jan 1993 13:13:33 GMT
Content-Type: text/html
Last-Modified: Mon, 5 Jan 2004 13:13:12 GMT
Content-Length: 105

<html><head><title>PHP HTTP SERVER RESPONSE</title></head><body>  Welcome to Php Http Server  </body></html>
s;

                    @fwrite($conn, $response);

                    fclose($conn);

                    unset($conn);
                }
                exit(0);
            }
        }
    }
}