<?php

namespace HttpServer\Module\Server;


class MultiThreadModel extends BaseModel
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        // 多线程模型 线程锁 pthread扩展
//        if ($mode == MULTI_THREAD_MODE) {
//            for ($i = 0; $i < 32; $i++) {
//                if ($thread = new Thread()) {
//                    while (1) {
//                        $conn = stream_socket_accept($this->serv);
//                        $request = fread($conn, 10);
//                        echo "connected\n";
//                        fclose($conn);
//                    }
//                    exit(0);
//                }
//            }
//        }
    }
}