<?php
/**
 * Created by PhpStorm.
 * User: chenhg5
 * Date: 2018/4/21
 * Time: 上午11:38
 */

namespace HttpServer\Module\Server;


class ReactorModel extends BaseModel
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}