<?php

namespace HttpServer\Module\Server;

class SingleThreadCoroutineModel extends BaseModel
{

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

    }

}